# Generated by Django 4.0.5 on 2022-07-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('comment', models.CharField(max_length=100)),
                ('keyS', models.TextField()),
                ('keyW', models.TextField()),
                ('emotion', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('diaryId', models.ForeignKey(db_column='diaryId', on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='diary.diary', unique=True)),
            ],
            options={
                'db_table': 'AI',
            },
        ),
    ]
