# Generated by Django 4.0.5 on 2022-07-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0004_diary_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('diaryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='diaryId_id', serialize=False, to='diary.diary')),
                ('image', models.TextField()),
                ('comment', models.CharField(max_length=100)),
                ('keyS', models.TextField()),
                ('keyW', models.TextField()),
                ('emotion', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'AI',
            },
        ),
    ]
