# Generated by Django 4.0.5 on 2022-07-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai',
            name='id',
        ),
        migrations.AlterField(
            model_name='ai',
            name='diaryId',
            field=models.ForeignKey(db_column='diaryId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='diary', serialize=False, to='diary.diary', unique=True),
        ),
    ]
