# Generated by Django 4.0.5 on 2022-07-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0004_alter_ai_comment_alter_ai_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
