# Generated by Django 4.0.5 on 2022-07-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('imageYN', models.BooleanField(default=True)),
                ('commentYN', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
