# Generated by Django 4.0.5 on 2022-07-13 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diaryId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('liked', models.BooleanField(default=False)),
                ('title', models.TextField(default='title')),
                ('contents', models.TextField()),
                ('weather', models.CharField(max_length=20)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user')),
            ],
            options={
                'db_table': 'Diary',
            },
        ),
    ]
