# Generated by Django 4.0.5 on 2022-07-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='like',
            new_name='liked',
        ),
    ]
