# Generated by Django 4.0.5 on 2022-07-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.TextField(default='title'),
        ),
    ]
